version: '3'

services:
   web:
      environment:
         - SECRET_KEY=local
      build: .
      command: bash -c "python3 manage.py migrate && python3 manage.py makemigrations coordinates && python3 manage.py makemigrations favourite_photos && python3 manage.py migrate && python3 manage.py loaddata apps/coordinates/fixtures/coordinates_fixtures.json && python3 manage.py runserver 0.0.0.0:8000"
      container_name: image_search_flickr
      volumes:
          - .:/code
      ports:
         - "8000:8000"
