export const PLACE_FETCH_START = 'PLACE_FETCH_START'
export const PLACE_FETCH_SUCCESS = 'PLACE_FETCH_SUCCESS'
export const PLACE_FETCH_FAIL = 'PLACE_FETCH_FAIL'

export const FETCH_FLICKR_DATA_START ='FETCH_FLICKR_DATA_START'
export const FETCH_FLICKR_DATA_SUCCESS ='FETCH_FLICKR_DATA_SUCCESS'
export const FETCH_FLICKR_DATA_FAIL ='FETCH_FLICKR_DATA_FAIL'
